import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import React, {useEffect} from 'react';

import Game from '../src/Game';

const useEventListener = (handler, deps = []) => {
  useEffect(() => {
    document.addEventListener("keydown", handler);
    return () => {
      document.removeEventListener("keydown", handler);
    };
  }, deps);
};

export default function Home() {

  useEventListener((evt) => {
    console.log(evt)});

  return (
    <div className={styles.container}>
      <Head>
        <title>Wordle Solver</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Wordle Solver
        </h1>

        <div id="root"><Game /></div>
        
      </main>
    </div>
  )
}

